<a href="https://colab.research.google.com/github/Gaurav4776608/Data-Cleaning-Processing-and-EDA/blob/main/Handling%20Missing%20Values/Part%203.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Handling Categorical Missing Values

These types of columns can be imputed by 2 techniques:
1. Filling with most frequent values
2. Fill the NaN values with 'Missing'

To fill up the NaN values with most frequent values we use mode().


For example, in a column called Country there are UAE, Japan, Germany categories. There are some NaN values and with the frequency of UAE is 30, Japan is 13 and Germany is 18 so the values will be replaced with UAE.


One thing should be taken care of is the difference in the highet and second highest frequency category should be high.


How should you decide?

Consider these three things:
1. Frequency gap: Is the most frequent category clearly ahead of the second most frequent category?
2. Missing percentage: How many values are missing? If 5 values are missing, mode imputation may have little impact. If 300 are missing, it may significantly distort the distribution.
3. Reason for missingness: Are values missing randomly, or could the missingness be related to the actual category?
4. Mode should be used when the missing value percentage is 5-10% of the overall data only.

Next technique is Filling NaN with 'Missng'

If the NaN values percentage is high or the NaN values are following a particular pattern (no randomness) then we fill NaN values with 'Missing' creating a new category

In [19]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [20]:
df = pd.read_csv('train.csv', usecols = ['GarageQual', 'FireplaceQu', 'SalePrice'])
df.head()

  FireplaceQu GarageQual  SalePrice
0         NaN         TA     208500
1          TA         TA     181500
2          TA         TA     223500
3          Gd         TA     140000
4          TA         TA     250000

In [21]:
df['FireplaceQu'].unique()

array([nan, 'TA', 'Gd', 'Fa', 'Ex', 'Po'], dtype=object)

In [22]:
df['GarageQual'].unique()

array(['TA', 'Fa', 'Gd', nan, 'Ex', 'Po'], dtype=object)

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   FireplaceQu  770 non-null    object
 1   GarageQual   1379 non-null   object
 2   SalePrice    1460 non-null   int64
dtypes: int64(1), object(2)
memory usage: 34.3+ KB

In [24]:
df.isnull().mean()*100

FireplaceQu    47.260274
GarageQual      5.547945
SalePrice       0.000000
dtype: float64

In [25]:
df['GarageQual'].value_counts()

GarageQual
TA    1311
Fa      48
Gd      14
Ex       3
Po       3
Name: count, dtype: int64

In [26]:
df['GarageQual'].fillna('TA', inplace = True)

/tmp/ipykernel_3383/2652256314.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['GarageQual'].fillna('TA', inplace = True)

In [27]:
df['GarageQual'].isnull().sum()

np.int64(0)

In [28]:
df['FireplaceQu'].value_counts()

FireplaceQu
Gd    380
TA    313
Fa     33
Ex     24
Po     20
Name: count, dtype: int64

In [29]:
df['FireplaceQu'].isnull().sum()

np.int64(690)

In [30]:
df['FireplaceQu'].fillna('Missing', inplace = True)

/tmp/ipykernel_3383/743166168.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['FireplaceQu'].fillna('Missing', inplace = True)